### ISSUE TITLE
wsmgr detecting active mysql database

### ISSUE THREAD

**Issue by ianbashford** [diladele/docker-cluster#4]
Hi Raphael,

I have websafety and mysql running in separate containers just fine - it connects when running the python scripts.  
However wsmgr isn't updating mysql with traffic, as it doesn't see the process. This message is in the GUI
No MySQL processes found. Error: the MySQL/MariaDB daemon is not running.

I guess it's using ps or similar to discover the process which it can't due to them running in a different process namespace.  
I tried faking a mysqld script that slept for ever, but it wasn't fooled...  can you give me any clues what it's looking for ?

**Comment by ra-at-diladele-com** [comment]
Hello Ian,

I will try to work with docker the following weeks and also will try to merge your previous requests. The Web UI just looks into the output of "ps -aux" to see the MySQL - which does not work as MySQL is in another container. Not sure what to do.

**Comment by ianbashford** [comment]
To try to understand what's going on, I compiled a no op program called mysqld and ran it as a mysql user -- seems much happier now :-)  
The trick here will be to get the process namespace sorted.  We can join the PID space in docker so I think there's a way through  - -it'd be interesting if you can help me understand what it's looking for.
For instance, I deduced that wsmgr is looking for a process called qlproxy that must be run by that user -- if the user's wrong ( root in docker for instance) then it won't detect it and the gui reports errors.
I linked the mysql and websafety containers so the 'hostname' of the database was available to websafety, which is what keeps that config clean.  I think we could join them in PID space too so those things resolve...   
I'll keep you updated.  Please let me know if you pursue any particular direction or if there's anything unpalatable for the product and I'll avoid...

**Comment by ra-at-diladele-com** [comment]
Thanks for the research! The Web UI is indeed looking for MySQL - see /opt/qlproxy/var/console/www/views.py the view name is View_MonitorInfo. 

The problem with microservice in a separate container approach is its nature - the Web UI does not yet know about Docker and tries to directly inspect the system. I had the feeling the Web UI needs to go to cloud somewhere with separate containers asking for configuration and reporting status back. But this is far from being implemented :(

**Comment by ianbashford** [comment]
Yeah -- I'm not sure we can share the PID namespace between two containers yet -- still looking.  However we can grant the container access to the host's process namespace.  
I'm still trying to see if there are negative consequences, but this kind of command works..
docker run  --link mysql:db -d --name websafety -p 81:80 -p 3128:3128 --pid=host -t websafety

It can see the host's processes with the ps command, and access the database via the hostname 'db' ( assuming your container is called 'mysql' ).  We can do this with docker compose as well, so should work well with the next step using haproxy...   few steps to go before we get there though... 
Thanks for the tips on the view;  I'll keep digging
